; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<test_hcsr04.cpp>
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    madhephaestus/ESP32Servo @ ^3.0.0

[env:test_hcsr04]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<test_hcsr04.cpp>

[env:test_servo]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<test_servo.cpp>
lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.0
